"""Reproduce the historical V20 migration from its original folder layout.

V20 has already run. Later folder moves belong in V23 or a newer migration;
never regenerate V20 against a changed tree because Flyway checks its checksum.
"""

import hashlib
import json
from pathlib import Path
import re
import zipfile
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/products/GBSE"
STATIC_DOCS = ROOT / "src/main/resources/static/docs"
OUTPUT = ROOT / "src/main/resources/db/migration/V20__folder_based_products.sql"
NS = {"s": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}

with zipfile.ZipFile(SOURCE / "GBSE-web.xlsx") as workbook:
    shared = ["".join(item.itertext()) for item in ET.fromstring(workbook.read("xl/sharedStrings.xml")).findall("s:si", NS)]
    sheet = ET.fromstring(workbook.read("xl/worksheets/sheet1.xml"))
    cells = {}
    for item in sheet.findall(".//s:sheetData/s:row/s:c", NS):
        value = item.find("s:v", NS)
        if value is not None:
            cells[item.attrib["r"]] = shared[int(value.text)] if item.get("t") == "s" else value.text


def cell(column, row):
    return cells.get(f"{column}{row}", "").strip()


def quote(value):
    return "NULL" if value is None else "'" + value.replace("'", "''") + "'"


def json_value(value):
    return quote(json.dumps(value, ensure_ascii=False)) if value else "NULL"


def content_lines(value):
    return [part.strip() for part in value.splitlines() if part.strip()]


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


STATIC_BY_HASH = {digest(file): file.name for file in STATIC_DOCS.glob("*.pdf")}

# Rows with direct PDFs only. Category slugs follow the existing V16/V19 tree.
# The six extra meter leaves are inserted below their existing group nodes.
PRODUCTS = [
    ("1. Plate Heat Exchanger", 2, "phe", "Plate Heat Exchanger"),
    ("2. Metering and Measuring/2.1.  Water Meter/2.1.1. Water Meter DN15-20 Single Jet", 5, "water-meter-dn15-20-single-jet", "Water meter DN15-20 single jet"),
    ("2. Metering and Measuring/2.1.  Water Meter/2.1.2. Water Meter DN15-50 Multi Jet", 6, "water-meter-dn15-50-multi-jet", "Water meter DN15-50 multi jet"),
    ("2. Metering and Measuring/2.1.  Water Meter/2.1.3. Water Meter DN50-200", 7, "water-meter-dn50-200", "Water meter DN50-200"),
    ("2. Metering and Measuring/2.2. Energy Meter/2.2.1. Energy meters DN15-32", 9, "energy-meters-dn15-32", "Energy meters DN15-32"),
    ("2. Metering and Measuring/2.2. Energy Meter/2.2.2. Energy meters DN15-100", 10, "energy-meters-dn15-100", "Energy meters DN15-100"),
    ("2. Metering and Measuring/2.2. Energy Meter/2.2.3. Energy meters DN125-800", 11, "energy-meters-dn125-800", "Energy meters DN125-800"),
    ("2. Metering and Measuring/2.3. Flowmeter", 12, "flowmeter", "Flow Meter DN15-2000"),
    ("3. Heatpump/3.1. Heatpump Air Source", 14, "heatpump-air-source", "Heatpump Air Source"),
    ("3. Heatpump/3.2. Heatpump all in one/3.2.1. CAHP-1.5HP", 15, "cahp-1-5hp", "CAHP-1.5HP"),
    ("3. Heatpump/3.2. Heatpump all in one/3.2.2. HPI Series", 16, "hpi-series", "HPI Series"),
    ("4. Automatic Control Valve/4.1. Anti water hammer valves", 18, "anti-water-hammer-valves", "N550 - Surge Anticipation Valve"),
    ("4. Automatic Control Valve/4.2. Pilot operated control valves", 19, "pilot-operated-control-valves", None),
    ("5. Control valve HVAC/5.1. Pressure Independent Control Valve", 21, "pressure-independent-control-valve", "Pressure Independent Control Valve"),
    ("5. Control valve HVAC/5.2. Motorized Butterfly Valve", 22, "motorized-butterfly-valve", "Motorized Butterfly Valve"),
    ("5. Control valve HVAC/5.3. Motorized Globe Valve", 23, "motorized-globe-valve", "Motorized Globe Valve"),
]

LEAVES = [
    ("water-meter-dn15-20-single-jet", "water-meter", "Water Meter DN15-20 Single Jet", 1),
    ("water-meter-dn15-50-multi-jet", "water-meter", "Water Meter DN15-50 Multi Jet", 2),
    ("water-meter-dn50-200", "water-meter", "Water Meter DN50-200", 3),
    ("energy-meters-dn15-32", "energy-meter", "Energy meters DN15-32", 1),
    ("energy-meters-dn15-100", "energy-meter", "Energy meters DN15-100", 2),
    ("energy-meters-dn125-800", "energy-meter", "Energy meters DN125-800", 3),
    ("cahp-1-5hp", "heatpump-all-in-one", "CAHP-1.5HP", 1),
    ("hpi-series", "heatpump-all-in-one", "HPI Series", 2),
]

expected = {path for path, *_ in PRODUCTS}
actual = {directory.relative_to(SOURCE).as_posix() for directory in SOURCE.rglob("*")
          if directory.is_dir() and any(directory.glob("*.pdf"))}
if actual != expected:
    raise RuntimeError(
        f"V20 is a historical snapshot; use a new migration for folder moves "
        f"(missing={expected - actual}, extra={actual - expected})")

sql = [
    "-- Generated by scripts/generate_folder_catalogue_migration.py from the folder tree and GBSE-web.xlsx.",
    "-- PDF bytes are never used as a content source; SHA-256 only verifies static copies.",
    "ALTER TABLE san_pham ADD COLUMN IF NOT EXISTS source_folder VARCHAR(500);",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_san_pham_source_folder ON san_pham(source_folder);",
]

for slug, parent, name, order in LEAVES:
    sql.append(f"""INSERT INTO category (parent_id, slug, name, sort_order)
SELECT p.id, {quote(slug)}, {quote(name)}, {order}
FROM category p WHERE p.slug = {quote(parent)}
ON CONFLICT (slug) DO NOTHING;""")
    sql.append(f"""DO $$ BEGIN
IF (SELECT count(*) FROM category c JOIN category p ON p.id = c.parent_id
    WHERE c.slug = {quote(slug)} AND c.name = {quote(name)} AND p.slug = {quote(parent)}) <> 1
THEN RAISE EXCEPTION 'Category location conflict: {slug}'; END IF;
END $$;""")

for folder, row, slug, old_name in PRODUCTS:
    source = SOURCE / folder
    pdfs = sorted(source.glob("*.pdf"), key=lambda file: file.name.casefold())
    if not pdfs:
        raise RuntimeError(f"No direct PDF in {folder}")
    # File names come from the direct-PDF folder. The workbook's 42I/84I
    # labels are typos; the source PDFs are correctly named 42E/84E.
    documents = []
    for pdf in pdfs:
        static_name = STATIC_BY_HASH.get(digest(pdf))
        if not static_name:
            raise RuntimeError(f"No identical public copy of {pdf}")
        documents.append({"label": pdf.stem, "url": f"/docs/{static_name}"})

    name = cell("B", row) or re.sub(r"^\d+(?:\.\d+)*\.\s*", "", source.name)
    # The workbook calls this row "Flowmeter"; the existing product has a more
    # specific name. The folder and workbook agree on the product identity.
    description = cell("D", row) or None
    applications = content_lines(cell("C", row))
    values = {
        "ten": quote(name), "short_text": "NULL", "mo_ta": quote(description),
        "applications": json_value(applications), "features": "NULL", "specs": "NULL",
        "documents": json_value(documents), "hinh_anh": "NULL", "visible": "TRUE",
    "source_folder": quote(folder),
    }
    assignments = ", ".join(f"{field} = {value}" for field, value in values.items())
    if old_name:
        sql.append(f"""DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = {quote(old_name)} OR p.source_folder = {quote(folder)}) AND c.slug IN ({quote(slug)},
      {quote('water-meter' if slug.startswith('water-meter-') else 'energy-meter' if slug.startswith('energy-meters-') else 'heatpump-all-in-one' if slug in ('cahp-1-5hp', 'hpi-series') else 'control-valve-hvac' if slug == 'motorized-globe-valve' else slug)})) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for {slug}'; END IF;
END $$;""")
        sql.append(f"""UPDATE san_pham p SET {assignments}
WHERE (p.ten = {quote(old_name)} AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ({quote(slug)},
      {quote('water-meter' if slug.startswith('water-meter-') else 'energy-meter' if slug.startswith('energy-meters-') else 'heatpump-all-in-one' if slug in ('cahp-1-5hp', 'hpi-series') else 'control-valve-hvac' if slug == 'motorized-globe-valve' else slug)})))
   OR p.source_folder = {quote(folder)};""")
    else:
        columns = ", ".join(values)
        selected = ", ".join(values.values())
        sql.append(f"""INSERT INTO san_pham ({columns}) VALUES ({selected})
ON CONFLICT (source_folder) DO UPDATE SET {assignments};""")

    # A product has one location in this source tree. Repoint only its own
    # catalogue links; the product row and unrelated records remain intact.
    sql.append(f"""DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = {quote(folder)}
  AND pc.category_id <> (SELECT id FROM category WHERE slug = {quote(slug)});
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = {quote(folder)} AND c.slug = {quote(slug)}
ON CONFLICT DO NOTHING;""")

# V19 had split single PDF folders into model cards. They must not appear next
# to the one card representing each direct-PDF folder.
for name in ("CAHP-MC-19", "CAHP-HC-42I", "CAHP-HC-84I", "VRB2 / VRB3", "VF2 / VF3"):
    sql.append(f"UPDATE san_pham SET visible = FALSE WHERE ten = {quote(name)} AND source_folder IS NULL;")

# The V19 catalogue leaves legacy ACV models visible in the pilot branch in
# some databases. Keep their data but prevent extra cards outside this tree.
sql.append("""UPDATE san_pham p SET visible = FALSE
WHERE p.source_folder IS NULL AND EXISTS (
  SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
  WHERE pc.product_id = p.id AND c.slug IN ('anti-water-hammer-valves', 'pilot-operated-control-valves'));
""")

OUTPUT.write_text("\n\n".join(sql) + "\n", encoding="utf-8")
print(f"Wrote {OUTPUT} for {len(PRODUCTS)} products and {sum(len(list((SOURCE / path).glob('*.pdf'))) for path, *_ in PRODUCTS)} PDFs")
