-- Generated by scripts/generate_folder_catalogue_migration.py from the folder tree and GBSE-web.xlsx.

-- PDF bytes are never used as a content source; SHA-256 only verifies static copies.

ALTER TABLE san_pham ADD COLUMN IF NOT EXISTS source_folder VARCHAR(500);

CREATE UNIQUE INDEX IF NOT EXISTS uq_san_pham_source_folder ON san_pham(source_folder);

INSERT INTO category (parent_id, slug, name, sort_order)
SELECT p.id, 'water-meter-dn15-20-single-jet', 'Water Meter DN15-20 Single Jet', 1
FROM category p WHERE p.slug = 'water-meter'
ON CONFLICT (slug) DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM category c JOIN category p ON p.id = c.parent_id
    WHERE c.slug = 'water-meter-dn15-20-single-jet' AND c.name = 'Water Meter DN15-20 Single Jet' AND p.slug = 'water-meter') <> 1
THEN RAISE EXCEPTION 'Category location conflict: water-meter-dn15-20-single-jet'; END IF;
END $$;

INSERT INTO category (parent_id, slug, name, sort_order)
SELECT p.id, 'water-meter-dn15-50-multi-jet', 'Water Meter DN15-50 Multi Jet', 2
FROM category p WHERE p.slug = 'water-meter'
ON CONFLICT (slug) DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM category c JOIN category p ON p.id = c.parent_id
    WHERE c.slug = 'water-meter-dn15-50-multi-jet' AND c.name = 'Water Meter DN15-50 Multi Jet' AND p.slug = 'water-meter') <> 1
THEN RAISE EXCEPTION 'Category location conflict: water-meter-dn15-50-multi-jet'; END IF;
END $$;

INSERT INTO category (parent_id, slug, name, sort_order)
SELECT p.id, 'water-meter-dn50-200', 'Water Meter DN50-200', 3
FROM category p WHERE p.slug = 'water-meter'
ON CONFLICT (slug) DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM category c JOIN category p ON p.id = c.parent_id
    WHERE c.slug = 'water-meter-dn50-200' AND c.name = 'Water Meter DN50-200' AND p.slug = 'water-meter') <> 1
THEN RAISE EXCEPTION 'Category location conflict: water-meter-dn50-200'; END IF;
END $$;

INSERT INTO category (parent_id, slug, name, sort_order)
SELECT p.id, 'energy-meters-dn15-32', 'Energy meters DN15-32', 1
FROM category p WHERE p.slug = 'energy-meter'
ON CONFLICT (slug) DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM category c JOIN category p ON p.id = c.parent_id
    WHERE c.slug = 'energy-meters-dn15-32' AND c.name = 'Energy meters DN15-32' AND p.slug = 'energy-meter') <> 1
THEN RAISE EXCEPTION 'Category location conflict: energy-meters-dn15-32'; END IF;
END $$;

INSERT INTO category (parent_id, slug, name, sort_order)
SELECT p.id, 'energy-meters-dn15-100', 'Energy meters DN15-100', 2
FROM category p WHERE p.slug = 'energy-meter'
ON CONFLICT (slug) DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM category c JOIN category p ON p.id = c.parent_id
    WHERE c.slug = 'energy-meters-dn15-100' AND c.name = 'Energy meters DN15-100' AND p.slug = 'energy-meter') <> 1
THEN RAISE EXCEPTION 'Category location conflict: energy-meters-dn15-100'; END IF;
END $$;

INSERT INTO category (parent_id, slug, name, sort_order)
SELECT p.id, 'energy-meters-dn125-800', 'Energy meters DN125-800', 3
FROM category p WHERE p.slug = 'energy-meter'
ON CONFLICT (slug) DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM category c JOIN category p ON p.id = c.parent_id
    WHERE c.slug = 'energy-meters-dn125-800' AND c.name = 'Energy meters DN125-800' AND p.slug = 'energy-meter') <> 1
THEN RAISE EXCEPTION 'Category location conflict: energy-meters-dn125-800'; END IF;
END $$;

INSERT INTO category (parent_id, slug, name, sort_order)
SELECT p.id, 'cahp-1-5hp', 'CAHP-1.5HP', 1
FROM category p WHERE p.slug = 'heatpump-all-in-one'
ON CONFLICT (slug) DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM category c JOIN category p ON p.id = c.parent_id
    WHERE c.slug = 'cahp-1-5hp' AND c.name = 'CAHP-1.5HP' AND p.slug = 'heatpump-all-in-one') <> 1
THEN RAISE EXCEPTION 'Category location conflict: cahp-1-5hp'; END IF;
END $$;

INSERT INTO category (parent_id, slug, name, sort_order)
SELECT p.id, 'hpi-series', 'HPI Series', 2
FROM category p WHERE p.slug = 'heatpump-all-in-one'
ON CONFLICT (slug) DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM category c JOIN category p ON p.id = c.parent_id
    WHERE c.slug = 'hpi-series' AND c.name = 'HPI Series' AND p.slug = 'heatpump-all-in-one') <> 1
THEN RAISE EXCEPTION 'Category location conflict: hpi-series'; END IF;
END $$;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'Plate Heat Exchanger' OR p.source_folder = '1. Plate Heat Exchanger') AND c.slug IN ('phe',
      'phe')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for phe'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Plate Heat Exchanger', short_text = NULL, mo_ta = 'Plate material: SS304, SS316L, Titan
Gasket material: EPDM, NBRH, Vitoni,...
Working pressure: 10 - 16 - 25 bar
Standard & approval: ISO 14001, ISO 9001, IATF 16949
PED, CRN, UL, ABS, BV, ASME, KRAIA, WRAS, DNV-GL, NSW, LR, RINA, WaterMark, AHRI etc.', applications = '["Hot water system", "Swimming pool", "HVAC system(pressure breaker)", "Food & Beverage"]', features = NULL, specs = NULL, documents = '[{"label": "Brochure_HEX", "url": "/docs/brochure-hex.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '1. Plate Heat Exchanger'
WHERE (p.ten = 'Plate Heat Exchanger' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('phe',
      'phe')))
   OR p.source_folder = '1. Plate Heat Exchanger';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '1. Plate Heat Exchanger'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'phe');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '1. Plate Heat Exchanger' AND c.slug = 'phe'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'Water meter DN15-20 single jet' OR p.source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.1. Water Meter DN15-20 Single Jet') AND c.slug IN ('water-meter-dn15-20-single-jet',
      'water-meter')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for water-meter-dn15-20-single-jet'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Water meter DN15-20 single jet', short_text = NULL, mo_ta = 'Model GSD8-RFM
Brand name: BMETERS 
DN15-20
Single Jet
Cold water: 0.1-50℃
Hot water: 30-90℃
Working pressure 16 bar
Direct reading on 8 numeric rolls
Anti magnetic fraud protection
Threading EN ISO 228-1:2003
Compatible modules: RFM-MB1, RFM-TX1
Certification MID, ACS, WRAS, ICIM', applications = '["Cold Water & Hot water supply system"]', features = NULL, specs = NULL, documents = '[{"label": "RFM-MB1", "url": "/docs/rfm-mb1.pdf"}, {"label": "RFM-TX1", "url": "/docs/rfm-tx1.pdf"}, {"label": "Water meter DN15-20 - GSD8-RFM", "url": "/docs/water-meter-dn15-20-gsd8-rfm.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.1. Water Meter DN15-20 Single Jet'
WHERE (p.ten = 'Water meter DN15-20 single jet' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('water-meter-dn15-20-single-jet',
      'water-meter')))
   OR p.source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.1. Water Meter DN15-20 Single Jet';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.1. Water Meter DN15-20 Single Jet'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'water-meter-dn15-20-single-jet');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.1. Water Meter DN15-20 Single Jet' AND c.slug = 'water-meter-dn15-20-single-jet'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'Water meter DN15-50 multi jet' OR p.source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.2. Water Meter DN15-50 Multi Jet') AND c.slug IN ('water-meter-dn15-50-multi-jet',
      'water-meter')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for water-meter-dn15-50-multi-jet'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Water meter DN15-50 multi jet', short_text = NULL, mo_ta = 'Model GMDM-I
Brand name: BMETERS 
DN15-50
Multi Jet
Cold water: 0.1-50℃
Hot water: 30-90℃
Working pressure 16 bar
Direct reading on 5 numeric rolls
Anti magnetic fraud protection
Threading EN ISO 228-1:2003
Compatible modules: IWM-TX3, IWM-LR3, IWM-MB3, IWM-PL3
Certification MID, ACS, WRAS, ICIM', applications = '["Cold Water & Hot water supply system"]', features = NULL, specs = NULL, documents = '[{"label": "IWM-LR3", "url": "/docs/iwm-lr3.pdf"}, {"label": "IWM-MB3", "url": "/docs/iwm-mb3.pdf"}, {"label": "IWM-PL3", "url": "/docs/iwm-pl3.pdf"}, {"label": "IWM-TX3", "url": "/docs/iwm-tx3.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.2. Water Meter DN15-50 Multi Jet'
WHERE (p.ten = 'Water meter DN15-50 multi jet' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('water-meter-dn15-50-multi-jet',
      'water-meter')))
   OR p.source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.2. Water Meter DN15-50 Multi Jet';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.2. Water Meter DN15-50 Multi Jet'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'water-meter-dn15-50-multi-jet');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.2. Water Meter DN15-50 Multi Jet' AND c.slug = 'water-meter-dn15-50-multi-jet'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'Water meter DN50-200' OR p.source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.3. Water Meter DN50-200') AND c.slug IN ('water-meter-dn50-200',
      'water-meter')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for water-meter-dn50-200'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Water meter DN50-200', short_text = NULL, mo_ta = 'Model WDE-K50
Brand name: BMETERS 
DN50-200
Woltmann type
Cold water: 0.1-50℃
Hot water: 30-90℃
Working pressure 16 bar
Direct reading on 7 numeric rolls
Anti magnetic fraud protection
Flange ISO 7005-2 / EN 1092-2 PN16
Compatible modules: IWM-TX4, IWM-LR4, IWM-MB4, IWM-PL4
Certification MID, ACS, WRAS, ICIM', applications = '["Cold Water & Hot water supply system"]', features = NULL, specs = NULL, documents = '[{"label": "IWM-MB4", "url": "/docs/iwm-mb4.pdf"}, {"label": "IWM-PL4", "url": "/docs/iwm-pl4.pdf"}, {"label": "IWM-TX4", "url": "/docs/iwm-tx4.pdf"}, {"label": "Water meter DN50-200 - WDE-K50", "url": "/docs/water-meter-dn50-200-wde-k50.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.3. Water Meter DN50-200'
WHERE (p.ten = 'Water meter DN50-200' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('water-meter-dn50-200',
      'water-meter')))
   OR p.source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.3. Water Meter DN50-200';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.3. Water Meter DN50-200'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'water-meter-dn50-200');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '2. Metering and Measuring/2.1.  Water Meter/2.1.3. Water Meter DN50-200' AND c.slug = 'water-meter-dn50-200'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'Energy meters DN15-32' OR p.source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.1. Energy meters DN15-32') AND c.slug IN ('energy-meters-dn15-32',
      'energy-meter')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for energy-meters-dn15-32'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Energy meters DN15-32', short_text = NULL, mo_ta = 'Energy meter DN15-32
Brand name: Danfoss
DN15-32
Ultrasonic compact energy meter
The energy meters consist of an ultrasonic flow sensor, a pair of Pt1000 temperature sensors and a calculator with integrated circuits for temperature measurement, flow calculation and energy calculation.
Power supply: 230V / 24V/ Battery (16+1 years)
Approvals: EN1434 class 2 and 3, MID (DK-0200-MI004-034), CPA according to JJG225 -2010
Communication: Wired M-Bus 
Connection: Thread 
Working pressure: PN25
Protection class IP65
Temperature senso: Pt1000
Flow sensor ultrasonic, accuracy ±2%', applications = '["HVAC system"]', features = NULL, specs = NULL, documents = '[{"label": "SonoSelect 10", "url": "/docs/sonoselect-10.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.1. Energy meters DN15-32'
WHERE (p.ten = 'Energy meters DN15-32' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('energy-meters-dn15-32',
      'energy-meter')))
   OR p.source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.1. Energy meters DN15-32';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.1. Energy meters DN15-32'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'energy-meters-dn15-32');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.1. Energy meters DN15-32' AND c.slug = 'energy-meters-dn15-32'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'Energy meters DN15-100' OR p.source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.2. Energy meters DN15-100') AND c.slug IN ('energy-meters-dn15-100',
      'energy-meter')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for energy-meters-dn15-100'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Energy meters DN15-100', short_text = NULL, mo_ta = 'Energy meter DN15-100
Brand name: Danfoss
Thread (G3/4 to G2) or flange (DN 20 to DN 100) connections
Ultrasonic compact energy meter
SonoMeter 40 energy meters consist of an ultrasonic flow sensor, a pair of Pt500 temperature sensors and a calculator with integrated circuits for temperature measurement, flow calculation and energy calculation.
Power supply: 230V / 24V/ Battery (15+1 years)
Approvals: EN1434 class 2 and 3, MID (DK-0200-MI004-034), CPA according to JJG225 -2010
Communication: Wired M-Bus / Modbus / Bacnet / LoRA-WAN / pulse output …
Connection: Thread / Flange
Working pressure: PN25
IP65
Temperature senso: Pt500 (Class B (EN60751))
Flow sensor ultrasonic, accuracy ±2%', applications = '["HVAC system"]', features = NULL, specs = NULL, documents = '[{"label": "SonoMeter 40", "url": "/docs/sonometer-40.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.2. Energy meters DN15-100'
WHERE (p.ten = 'Energy meters DN15-100' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('energy-meters-dn15-100',
      'energy-meter')))
   OR p.source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.2. Energy meters DN15-100';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.2. Energy meters DN15-100'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'energy-meters-dn15-100');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.2. Energy meters DN15-100' AND c.slug = 'energy-meters-dn15-100'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'Energy meters DN125-800' OR p.source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.3. Energy meters DN125-800') AND c.slug IN ('energy-meters-dn125-800',
      'energy-meter')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for energy-meters-dn125-800'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Energy meters DN125-800', short_text = NULL, mo_ta = 'Energy meter DN125-800
Brand name: Danfoss
Flange connection
Ultrasonic compact energy meter
Supercal 5 and Sono3500CT is energy meters consist of an ultrasonic flow sensor, a pair of Pt500 temperature sensors and a calculator with integrated circuits for temperature measurement, flow calculation and energy calculation.
Power supply: 230V / Battery (12+1 years)
Communication: Wired M-Bus / Modbus / Bacnet / LoRA-WAN …
Working pressure: PN16 / PN25
IP65
Temperature senso: Pt500 (Class B (EN60751))
Flow sensor ultrasonic, accuracy ±2%', applications = '["HVAC system"]', features = NULL, specs = NULL, documents = '[{"label": "Sono3500CT", "url": "/docs/sono3500ct.pdf"}, {"label": "Supercal 5", "url": "/docs/supercal-5.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.3. Energy meters DN125-800'
WHERE (p.ten = 'Energy meters DN125-800' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('energy-meters-dn125-800',
      'energy-meter')))
   OR p.source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.3. Energy meters DN125-800';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.3. Energy meters DN125-800'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'energy-meters-dn125-800');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '2. Metering and Measuring/2.2. Energy Meter/2.2.3. Energy meters DN125-800' AND c.slug = 'energy-meters-dn125-800'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'Flow Meter DN15-2000' OR p.source_folder = '2. Metering and Measuring/2.3. Flowmeter') AND c.slug IN ('flowmeter',
      'flowmeter')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for flowmeter'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Flowmeter', short_text = NULL, mo_ta = 'Flow Meter DN15-2000
Brand name: BMETERS 
DN15-2000
Electromagnectic flow meter
Temperature range: -40 - 80 ℃
Working pressure 10-16-25-40 bar
Anti magnetic fraud protection
Available flange: UNI EN 1092, ANSI150, ANSI300, DIN2501, BS45404, AWWA
Protection class IP68
Available linings PTFE, EBANITE
Pipes material AISI304 (AISI316L upon request)
Electrodes material HASTELLOY C
Display LCD graphic 128x64 pixels retrofit
Out signal: 4-20 mA, pulse, frequency. Modbus RTU RS485, Hart protocol', applications = '["HVAC system"]', features = NULL, specs = NULL, documents = '[{"label": "MAG-C", "url": "/docs/mag-c.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '2. Metering and Measuring/2.3. Flowmeter'
WHERE (p.ten = 'Flow Meter DN15-2000' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('flowmeter',
      'flowmeter')))
   OR p.source_folder = '2. Metering and Measuring/2.3. Flowmeter';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '2. Metering and Measuring/2.3. Flowmeter'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'flowmeter');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '2. Metering and Measuring/2.3. Flowmeter' AND c.slug = 'flowmeter'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'Heatpump Air Source' OR p.source_folder = '3. Heatpump/3.1. Heatpump Air Source') AND c.slug IN ('heatpump-air-source',
      'heatpump-air-source')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for heatpump-air-source'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Heatpump Air Source', short_text = NULL, mo_ta = 'Heatpump air to water
Capacity range: 19 - 42 - 84 kW
Type: Air source heatpump
Voltage/Phase: 380V/3N～/50Hz
COP > 4
Max. out put water Temperature: 55℃
Refrigerant: R410A', applications = '["Hot water system"]', features = NULL, specs = NULL, documents = '[{"label": "CAHP-HC-42E", "url": "/docs/cahp-hc-42e.pdf"}, {"label": "CAHP-HC-84E", "url": "/docs/cahp-hc-84e.pdf"}, {"label": "CAHP-MC-19 Specification", "url": "/docs/cahp-mc-19-specification.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '3. Heatpump/3.1. Heatpump Air Source'
WHERE (p.ten = 'Heatpump Air Source' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('heatpump-air-source',
      'heatpump-air-source')))
   OR p.source_folder = '3. Heatpump/3.1. Heatpump Air Source';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '3. Heatpump/3.1. Heatpump Air Source'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'heatpump-air-source');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '3. Heatpump/3.1. Heatpump Air Source' AND c.slug = 'heatpump-air-source'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'CAHP-1.5HP' OR p.source_folder = '3. Heatpump/3.2. Heatpump all in one/3.2.1. CAHP-1.5HP') AND c.slug IN ('cahp-1-5hp',
      'heatpump-all-in-one')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for cahp-1-5hp'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Heatpump all in one', short_text = NULL, mo_ta = 'CAHP-1.5HP
Unique heat exchanger design, heat pump water temperature to 65˚C
Energy saving, fast heating, electric back up and standard modes for choosing
Smart control to avoid cold water mixing LCD display
R134agreen refrigerant
Integrate design for outdoor installation
Available in 300 & 450 Litre storage', applications = '["Hot water system"]', features = NULL, specs = NULL, documents = '[{"label": "CAHP-1.5HP", "url": "/docs/cahp-1-5hp.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '3. Heatpump/3.2. Heatpump all in one/3.2.1. CAHP-1.5HP'
WHERE (p.ten = 'CAHP-1.5HP' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('cahp-1-5hp',
      'heatpump-all-in-one')))
   OR p.source_folder = '3. Heatpump/3.2. Heatpump all in one/3.2.1. CAHP-1.5HP';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '3. Heatpump/3.2. Heatpump all in one/3.2.1. CAHP-1.5HP'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'cahp-1-5hp');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '3. Heatpump/3.2. Heatpump all in one/3.2.1. CAHP-1.5HP' AND c.slug = 'cahp-1-5hp'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'HPI Series' OR p.source_folder = '3. Heatpump/3.2. Heatpump all in one/3.2.2. HPI Series') AND c.slug IN ('hpi-series',
      'heatpump-all-in-one')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for hpi-series'; END IF;
END $$;

UPDATE san_pham p SET ten = 'HPI Series', short_text = NULL, mo_ta = 'HPI Series
Heat pump water temperature 55˚C,
Max water temperature 75˚C
Heat pump input 460w, COP 3.8
Two elements back up for quick recovery
Patented AES energy saving system
Timer setting
Remote control
PS safety system
R134a Green refrigerant
Volume: 150 / 180L', applications = NULL, features = NULL, specs = NULL, documents = '[{"label": "HPI Series", "url": "/docs/hpi-series.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '3. Heatpump/3.2. Heatpump all in one/3.2.2. HPI Series'
WHERE (p.ten = 'HPI Series' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('hpi-series',
      'heatpump-all-in-one')))
   OR p.source_folder = '3. Heatpump/3.2. Heatpump all in one/3.2.2. HPI Series';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '3. Heatpump/3.2. Heatpump all in one/3.2.2. HPI Series'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'hpi-series');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '3. Heatpump/3.2. Heatpump all in one/3.2.2. HPI Series' AND c.slug = 'hpi-series'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'N550 - Surge Anticipation Valve' OR p.source_folder = '4. Automatic Control Valve/4.1. Anti water hammer valves') AND c.slug IN ('anti-water-hammer-valves',
      'anti-water-hammer-valves')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for anti-water-hammer-valves'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Anti water hammer valves', short_text = NULL, mo_ta = 'Anti water hammer valves
Nominal diameter: DN40 – DN1600
Type of connection: Threaded and flange
Media temperature:
– Water: 0°C to 70°C
– Fuel: -40°C to 70°C
Pressure range: 
ISO PN10/PN16/PN25 – ANSI Class 125/150/300
JIS 10K/16K – KS Table D/E, KS4087 PN16
Permissible medium/application:
Pressure, Flow, Level control, Smart control in municipality.
Water, pumping station, building, fire protection, irrigation, water treatment.
Fuel, Sea water, Clear water
Flange standard: 
EN 1092-2 – ISO 7005-2 – ANSI or JIS – KS2129 or KS4087', applications = '["Water supply system", "Anti fire fighting system"]', features = NULL, specs = NULL, documents = '[{"label": "N550_EN", "url": "/docs/n550-en.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '4. Automatic Control Valve/4.1. Anti water hammer valves'
WHERE (p.ten = 'N550 - Surge Anticipation Valve' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('anti-water-hammer-valves',
      'anti-water-hammer-valves')))
   OR p.source_folder = '4. Automatic Control Valve/4.1. Anti water hammer valves';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '4. Automatic Control Valve/4.1. Anti water hammer valves'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'anti-water-hammer-valves');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '4. Automatic Control Valve/4.1. Anti water hammer valves' AND c.slug = 'anti-water-hammer-valves'
ON CONFLICT DO NOTHING;

INSERT INTO san_pham (ten, short_text, mo_ta, applications, features, specs, documents, hinh_anh, visible, source_folder) VALUES ('Pilot operated control valves', NULL, 'Neptune – Automatic control valves
Nominal diameter: DN40 – DN1600
Media temperature: water: 0°C to 70°C and fuel: -40°C to 70°C
Pressure range: 10/16/25/40 bar
Permissible medium/application:
– Pressure, Flow, Level control, Smart control in municipality
– Water, pumping station, building, fire protection, irrigation, water treatment
– Fuel
– Sea water
– Clear water
Connection: PN10/16/25
Flange standard
EN 1092-2
ISO 7005-2
ANSI or JIS
KS2129 or KS4087
Design standard EN 1074-5
Test standard ISO 5208 and EN12266-1', '["Water supply system", "Anti fire fighting system"]', NULL, NULL, '[{"label": "Brochure_Neptune_EN", "url": "/docs/brochure-neptune-en.pdf"}]', NULL, TRUE, '4. Automatic Control Valve/4.2. Pilot operated control valves')
ON CONFLICT (source_folder) DO UPDATE SET ten = 'Pilot operated control valves', short_text = NULL, mo_ta = 'Neptune – Automatic control valves
Nominal diameter: DN40 – DN1600
Media temperature: water: 0°C to 70°C and fuel: -40°C to 70°C
Pressure range: 10/16/25/40 bar
Permissible medium/application:
– Pressure, Flow, Level control, Smart control in municipality
– Water, pumping station, building, fire protection, irrigation, water treatment
– Fuel
– Sea water
– Clear water
Connection: PN10/16/25
Flange standard
EN 1092-2
ISO 7005-2
ANSI or JIS
KS2129 or KS4087
Design standard EN 1074-5
Test standard ISO 5208 and EN12266-1', applications = '["Water supply system", "Anti fire fighting system"]', features = NULL, specs = NULL, documents = '[{"label": "Brochure_Neptune_EN", "url": "/docs/brochure-neptune-en.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '4. Automatic Control Valve/4.2. Pilot operated control valves';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '4. Automatic Control Valve/4.2. Pilot operated control valves'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'pilot-operated-control-valves');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '4. Automatic Control Valve/4.2. Pilot operated control valves' AND c.slug = 'pilot-operated-control-valves'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'Pressure Independent Control Valve' OR p.source_folder = '5. Control valve HVAC/5.1. Pressure Independent Control Valve') AND c.slug IN ('pressure-independent-control-valve',
      'pressure-independent-control-valve')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for pressure-independent-control-valve'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Pressure Independent Control Valve', short_text = NULL, mo_ta = 'Pressure independent control valve
Size DN15-250
Working pressure: 
DN15-32: 25 bar
DN40-250: 16 bar
Differential pressure range: 16-600 kpa
Connection:
DN15-50: Thread connection (ISO 228-1)
DN65:250: Flange connection (EN 1092-1, -2)
Flowrate range: Detail in datasheet
Control: On/Off or modulating
Type: Thermal / Gear / Digital
Power supply: 230V / 24V', applications = '["HVAC system"]', features = NULL, specs = NULL, documents = '[{"label": "AB-QM 4.0 Flexo 80", "url": "/docs/ab-qm-4-0-flexo-80.pdf"}, {"label": "ABQM 4.0", "url": "/docs/abqm-4-0.pdf"}, {"label": "Actuator selection for PICV", "url": "/docs/actuator-selection-for-picv.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '5. Control valve HVAC/5.1. Pressure Independent Control Valve'
WHERE (p.ten = 'Pressure Independent Control Valve' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('pressure-independent-control-valve',
      'pressure-independent-control-valve')))
   OR p.source_folder = '5. Control valve HVAC/5.1. Pressure Independent Control Valve';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '5. Control valve HVAC/5.1. Pressure Independent Control Valve'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'pressure-independent-control-valve');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '5. Control valve HVAC/5.1. Pressure Independent Control Valve' AND c.slug = 'pressure-independent-control-valve'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'Motorized Butterfly Valve' OR p.source_folder = '5. Control valve HVAC/5.2. Motorized Butterfly Valve') AND c.slug IN ('motorized-butterfly-valve',
      'motorized-butterfly-valve')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for motorized-butterfly-valve'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Motorized Butterfly Valve', short_text = NULL, mo_ta = 'Motorized butterfly valve
Valve body: 
Wafer type
DN32 - 600
Max working pressure 16 bar
Body material: GGG40 nodular cast iron
Disc material: Wafer type: DN32: 304SS; DN40-600: GGG40+Nylon; Lug/Flange: 304SS
Acutuator:
On/Off or Modulating
Power supply: 230VAC
IP67', applications = '["HVAC system"]', features = NULL, specs = NULL, documents = '[{"label": "Butterfly valve VFH2_DN32-600", "url": "/docs/butterfly-valve-vfh2-dn32-600.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '5. Control valve HVAC/5.2. Motorized Butterfly Valve'
WHERE (p.ten = 'Motorized Butterfly Valve' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('motorized-butterfly-valve',
      'motorized-butterfly-valve')))
   OR p.source_folder = '5. Control valve HVAC/5.2. Motorized Butterfly Valve';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '5. Control valve HVAC/5.2. Motorized Butterfly Valve'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'motorized-butterfly-valve');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '5. Control valve HVAC/5.2. Motorized Butterfly Valve' AND c.slug = 'motorized-butterfly-valve'
ON CONFLICT DO NOTHING;

DO $$ BEGIN
IF (SELECT count(*) FROM san_pham p JOIN product_category pc ON pc.product_id = p.id
    JOIN category c ON c.id = pc.category_id
    WHERE (p.ten = 'Motorized Globe Valve' OR p.source_folder = '5. Control valve HVAC/5.3. Motorized Globe Valve') AND c.slug IN ('motorized-globe-valve',
      'control-valve-hvac')) <> 1
THEN RAISE EXCEPTION 'Expected exactly one existing product for motorized-globe-valve'; END IF;
END $$;

UPDATE san_pham p SET ten = 'Motorized Globe Valve', short_text = NULL, mo_ta = 'Motorized globe valve 2 way - 3 way
Model: 
DN15-50: VRB2 - VRB3
DN65-150: VF2 - VF3
Material:
DN15-50: Red bronze CuSn5ZN5Pb5 (Rg5)
DN65-150: EN-GJL-250 (GG-25) / EN-GJS-400-18-LT / EN-GJL-250 (GG-25)
Working pressure: 16 bar
Actuator: Modulating control / 24V
Input signal: 0(2)-10V / 0(4)-20 mA', applications = '["HVAC system"]', features = NULL, specs = NULL, documents = '[{"label": "VF2 + VF3", "url": "/docs/vf2-plus-vf3.pdf"}, {"label": "VRB2 VRB3", "url": "/docs/vrb2-vrb3.pdf"}]', hinh_anh = NULL, visible = TRUE, source_folder = '5. Control valve HVAC/5.3. Motorized Globe Valve'
WHERE (p.ten = 'Motorized Globe Valve' AND p.source_folder IS NULL AND EXISTS (
    SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
    WHERE pc.product_id = p.id AND c.slug IN ('motorized-globe-valve',
      'control-valve-hvac')))
   OR p.source_folder = '5. Control valve HVAC/5.3. Motorized Globe Valve';

DELETE FROM product_category pc USING san_pham p
WHERE pc.product_id = p.id AND p.source_folder = '5. Control valve HVAC/5.3. Motorized Globe Valve'
  AND pc.category_id <> (SELECT id FROM category WHERE slug = 'motorized-globe-valve');
INSERT INTO product_category (product_id, category_id)
SELECT p.id, c.id FROM san_pham p, category c
WHERE p.source_folder = '5. Control valve HVAC/5.3. Motorized Globe Valve' AND c.slug = 'motorized-globe-valve'
ON CONFLICT DO NOTHING;

UPDATE san_pham SET visible = FALSE WHERE ten = 'CAHP-MC-19' AND source_folder IS NULL;

UPDATE san_pham SET visible = FALSE WHERE ten = 'CAHP-HC-42I' AND source_folder IS NULL;

UPDATE san_pham SET visible = FALSE WHERE ten = 'CAHP-HC-84I' AND source_folder IS NULL;

UPDATE san_pham SET visible = FALSE WHERE ten = 'VRB2 / VRB3' AND source_folder IS NULL;

UPDATE san_pham SET visible = FALSE WHERE ten = 'VF2 / VF3' AND source_folder IS NULL;

UPDATE san_pham p SET visible = FALSE
WHERE p.source_folder IS NULL AND EXISTS (
  SELECT 1 FROM product_category pc JOIN category c ON c.id = pc.category_id
  WHERE pc.product_id = p.id AND c.slug IN ('anti-water-hammer-valves', 'pilot-operated-control-valves'));

